In [1]:
import json

with open('../data/tacred/train.json', 'r') as f:
    data1= json.load(f)
with open('../data/tacred/dev.json', 'r') as f:
    data2 = json.load(f)
with open('../data/tacred/test.json', 'r') as f:
    data3 = json.load(f)
data=[]
data.extend(data1)
data.extend(data2)
data.extend(data3)

In [7]:
data[0]

{'id': '61b3a5c8c9a882dcfcd2',
 'docid': 'AFP_ENG_20070218.0019.LDC2009T13',
 'relation': 'org:founded_by',
 'token': ['Tom',
  'Thabane',
  'resigned',
  'in',
  'October',
  'last',
  'year',
  'to',
  'form',
  'the',
  'All',
  'Basotho',
  'Convention',
  '-LRB-',
  'ABC',
  '-RRB-',
  ',',
  'crossing',
  'the',
  'floor',
  'with',
  '17',
  'members',
  'of',
  'parliament',
  ',',
  'causing',
  'constitutional',
  'monarch',
  'King',
  'Letsie',
  'III',
  'to',
  'dissolve',
  'parliament',
  'and',
  'call',
  'the',
  'snap',
  'election',
  '.'],
 'subj_start': 10,
 'subj_end': 12,
 'obj_start': 0,
 'obj_end': 1,
 'subj_type': 'ORGANIZATION',
 'obj_type': 'PERSON',
 'stanford_pos': ['NNP',
  'NNP',
  'VBD',
  'IN',
  'NNP',
  'JJ',
  'NN',
  'TO',
  'VB',
  'DT',
  'DT',
  'NNP',
  'NNP',
  '-LRB-',
  'NNP',
  '-RRB-',
  ',',
  'VBG',
  'DT',
  'NN',
  'IN',
  'CD',
  'NNS',
  'IN',
  'NN',
  ',',
  'VBG',
  'JJ',
  'NN',
  'NNP',
  'NNP',
  'NNP',
  'TO',
  'VB',
  'NN'

In [2]:
for d in data:
    ss, se = d['subj_start'], d['subj_end']
    os, oe = d['obj_start'], d['obj_end']
    tokens = d['token']
    print(tokens[ss:se+1])
    print(tokens[os:oe+1])
    print(' '.join(tokens))
    break


['All', 'Basotho', 'Convention']
['Tom', 'Thabane']
Tom Thabane resigned in October last year to form the All Basotho Convention -LRB- ABC -RRB- , crossing the floor with 17 members of parliament , causing constitutional monarch King Letsie III to dissolve parliament and call the snap election .


In [6]:
import nltk
from nltk.stem import WordNetLemmatizer
lemm = WordNetLemmatizer()
count=0
for item in data:
    if item['relation'] == "org:political/religious_affiliation":
        # if item['obj_type']=='NATIONALITY':
            subj = ' '.join(item['token'][item['subj_start'] : item['subj_end']+1])
            obj = ' '.join(item['token'][item['obj_start'] : item['obj_end']+1])
            print(' '.join(item['token']))
            print(subj)
            print(obj)
            print(item['subj_type'])
            print(item['obj_type'])
            print('_________________________')

Baathists , Sunni and Shia alike , Muslim and Christian alike , have been hunt , tortured and killed by the US Occupation , its puppet government of sectarian warlords taking orders from their Iranian masters , the sectarian pro-Iranian militias , especially the Badr Brigades and the Mahdi Army , and yes , with the help of Iran as well .
Badr Brigades
Muslim
ORGANIZATION
RELIGION
_________________________
There was `` nothing unusual '' about bishops reporting to the KGB , said Xenia Dennen , head of the Keston Institute , a British institute for the study of religion in communist countries .
KGB
communist
ORGANIZATION
RELIGION
_________________________
And in perhaps a sign that she is also thinking about 2012 , she has been sticking close to her base , granting taped radio interviews to Dr. James Dobson of the Christian conservative group Focus on the Family , and Michael Medved , the conservative commentator .
Focus on the Family
Christian
ORGANIZATION
RELIGION
_____________________

In [89]:
subj_type_dict = {}
obj_type_dict = {}
class_dict = {}
ner_dict = []
for item in data1:
    if item['subj_type'] not in subj_type_dict:
        subj_type_dict[item['subj_type']] = 1
    else:
        subj_type_dict[item['subj_type']] += 1
    if item['obj_type'] not in obj_type_dict:
        obj_type_dict[item['obj_type']] = 1
    else:
        obj_type_dict[item['obj_type']] += 1
    if item['relation'] not in class_dict:
        class_dict[item['relation']] = 1
    else:
        class_dict[item['relation']] += 1
    for x in item['stanford_ner']:
        if x not in ner_dict:
            ner_dict.append(x)
    

In [90]:
ner_dict

['PERSON',
 'O',
 'DATE',
 'ORGANIZATION',
 'NUMBER',
 'DURATION',
 'MISC',
 'MONEY',
 'LOCATION',
 'ORDINAL',
 'SET',
 'TIME',
 'PERCENT']

In [91]:
subj_type_dict

{'ORGANIZATION': 30570, 'PERSON': 37554}

In [92]:
obj_type_dict

{'PERSON': 20749,
 'ORGANIZATION': 13375,
 'NUMBER': 5643,
 'DATE': 8009,
 'NATIONALITY': 945,
 'LOCATION': 2655,
 'TITLE': 4621,
 'CITY': 2628,
 'MISC': 1918,
 'COUNTRY': 3679,
 'CRIMINAL_CHARGE': 205,
 'RELIGION': 364,
 'DURATION': 834,
 'URL': 195,
 'STATE_OR_PROVINCE': 1601,
 'IDEOLOGY': 206,
 'CAUSE_OF_DEATH': 497}

In [93]:
relation_type_dict = {k:{} for k in class_dict.keys()}
for item in data:
    txt = (item['subj_type'], item['obj_type'])
    if item['relation']=='no_relation':
        continue
    if txt not in relation_type_dict[item['relation']]:
        relation_type_dict[item['relation']][txt]=1
    else:
        relation_type_dict[item['relation']][txt]+=1

In [94]:
for k,v in relation_type_dict.items():
        print(k)
        print(v)
        print('__________')

org:founded_by
{('ORGANIZATION', 'PERSON'): 268}
__________
no_relation
{}
__________
per:employee_of
{('PERSON', 'ORGANIZATION'): 2160, ('PERSON', 'LOCATION'): 3}
__________
org:alternate_names
{('ORGANIZATION', 'ORGANIZATION'): 1326, ('ORGANIZATION', 'MISC'): 33}
__________
per:cities_of_residence
{('PERSON', 'CITY'): 624, ('PERSON', 'LOCATION'): 118}
__________
per:children
{('PERSON', 'PERSON'): 347}
__________
per:title
{('PERSON', 'TITLE'): 3862}
__________
per:siblings
{('PERSON', 'PERSON'): 250}
__________
per:religion
{('PERSON', 'RELIGION'): 153}
__________
per:age
{('PERSON', 'NUMBER'): 728, ('PERSON', 'DURATION'): 105}
__________
org:website
{('ORGANIZATION', 'URL'): 223}
__________
per:stateorprovinces_of_residence
{('PERSON', 'STATE_OR_PROVINCE'): 451, ('PERSON', 'LOCATION'): 33}
__________
org:member_of
{('ORGANIZATION', 'ORGANIZATION'): 132, ('ORGANIZATION', 'LOCATION'): 13, ('ORGANIZATION', 'COUNTRY'): 21, ('ORGANIZATION', 'STATE_OR_PROVINCE'): 5}
__________
org:top_me

In [95]:
entity_pair = []
for subj in subj_type_dict.keys():
    for obj in obj_type_dict.keys():
        entity_pair.append((subj,obj))

In [96]:
entity_pair_relation = {k:[] for k in entity_pair}
for k,v in relation_type_dict.items():
    for e in v.keys():
        entity_pair_relation[e].append(k)

In [97]:
len(entity_pair_relation)

34

In [98]:
entity_pair_relation

{('ORGANIZATION', 'PERSON'): ['org:founded_by',
  'org:top_members/employees',
  'org:shareholders'],
 ('ORGANIZATION', 'ORGANIZATION'): ['org:alternate_names',
  'org:member_of',
  'org:members',
  'org:parents',
  'org:subsidiaries',
  'org:shareholders'],
 ('ORGANIZATION', 'NUMBER'): ['org:number_of_employees/members'],
 ('ORGANIZATION', 'DATE'): ['org:dissolved', 'org:founded'],
 ('ORGANIZATION', 'NATIONALITY'): [],
 ('ORGANIZATION', 'LOCATION'): ['org:member_of',
  'org:city_of_headquarters',
  'org:country_of_headquarters',
  'org:stateorprovince_of_headquarters',
  'org:parents',
  'org:subsidiaries'],
 ('ORGANIZATION', 'TITLE'): [],
 ('ORGANIZATION', 'CITY'): ['org:city_of_headquarters'],
 ('ORGANIZATION', 'MISC'): ['org:alternate_names'],
 ('ORGANIZATION', 'COUNTRY'): ['org:member_of',
  'org:members',
  'org:country_of_headquarters',
  'org:parents',
  'org:subsidiaries'],
 ('ORGANIZATION', 'CRIMINAL_CHARGE'): [],
 ('ORGANIZATION', 'RELIGION'): ['org:political/religious_affil

In [34]:
import pickle
with open('../data/relation/entity_pair_relation.pkl', 'wb') as f:
    pickle.dump(entity_pair_relation, f)

In [36]:
entity_pair_num = {k:0 for k in entity_pair}
for item in data:
    entity_pair_num[(item['subj_type'], item['obj_type'])]+=1

In [37]:
entity_pair_num

{('ORGANIZATION', 'PERSON'): 10051,
 ('ORGANIZATION', 'ORGANIZATION'): 12198,
 ('ORGANIZATION', 'NUMBER'): 4854,
 ('ORGANIZATION', 'DATE'): 6696,
 ('ORGANIZATION', 'NATIONALITY'): 0,
 ('ORGANIZATION', 'LOCATION'): 1834,
 ('ORGANIZATION', 'TITLE'): 0,
 ('ORGANIZATION', 'CITY'): 1899,
 ('ORGANIZATION', 'MISC'): 1395,
 ('ORGANIZATION', 'COUNTRY'): 3353,
 ('ORGANIZATION', 'CRIMINAL_CHARGE'): 0,
 ('ORGANIZATION', 'RELIGION'): 282,
 ('ORGANIZATION', 'DURATION'): 0,
 ('ORGANIZATION', 'URL'): 347,
 ('ORGANIZATION', 'STATE_OR_PROVINCE'): 991,
 ('ORGANIZATION', 'IDEOLOGY'): 270,
 ('ORGANIZATION', 'CAUSE_OF_DEATH'): 0,
 ('PERSON', 'PERSON'): 22288,
 ('PERSON', 'ORGANIZATION'): 7630,
 ('PERSON', 'NUMBER'): 3781,
 ('PERSON', 'DATE'): 6120,
 ('PERSON', 'NATIONALITY'): 1745,
 ('PERSON', 'LOCATION'): 2037,
 ('PERSON', 'TITLE'): 7296,
 ('PERSON', 'CITY'): 2314,
 ('PERSON', 'MISC'): 1414,
 ('PERSON', 'COUNTRY'): 2538,
 ('PERSON', 'CRIMINAL_CHARGE'): 609,
 ('PERSON', 'RELIGION'): 402,
 ('PERSON', 'DURATI

In [5]:
l2i = {'no_relation': 0, 
                            'per:title': 1, 
                            'org:top_members/employees': 2, 
                            'per:employee_of': 3, 
                            'org:alternate_names': 4, 
                            'org:country_of_headquarters': 5, 
                            'per:countries_of_residence': 6, 
                            'org:city_of_headquarters': 7, 
                            'per:cities_of_residence': 8, 
                            'per:age': 9, 
                            'per:stateorprovinces_of_residence': 10, 
                            'per:origin': 11, 
                            'org:subsidiaries': 12, 
                            'org:parents': 13, 
                            'per:spouse': 14, 
                            'org:stateorprovince_of_headquarters': 15, 
                            'per:children': 16, 
                            'per:other_family': 17, 
                            'per:alternate_names': 18, 
                            'org:members': 19, 
                            'per:siblings': 20, 
                            'per:schools_attended': 21, 
                            'per:parents': 22, 
                            'per:date_of_death': 23, 
                            'org:member_of': 24, 
                            'org:founded_by': 25, 
                            'org:website': 26, 
                            'per:cause_of_death': 27, 
                            'org:political/religious_affiliation': 28, 
                            'org:founded': 29, 
                            'per:city_of_death': 30, 
                            'org:shareholders': 31, 
                            'org:number_of_employees/members': 32, 
                            'per:date_of_birth': 33, 
                            'per:city_of_birth': 34, 
                            'per:charges': 35, 
                            'per:stateorprovince_of_death': 36, 
                            'per:religion': 37, 
                            'per:stateorprovince_of_birth': 38, 
                            'per:country_of_birth': 39, 
                            'org:dissolved': 40, 
                            'per:country_of_death': 41} 

In [6]:
import json

with open('../data/relation/l2i.json', 'w') as f:
    json.dump(l2i, f, indent = '\t')

In [38]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained('ynie/roberta-large-snli_mnli_fever_anli_R1_R2_R3-nli')

Downloading: 100%|██████████| 703/703 [00:00<00:00, 182kB/s]
Downloading: 100%|██████████| 1.33G/1.33G [02:42<00:00, 8.78MB/s] 
Some weights of the model checkpoint at ynie/roberta-large-snli_mnli_fever_anli_R1_R2_R3-nli were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [39]:
model

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 1024, padding_idx=1)
      (position_embeddings): Embedding(514, 1024, padding_idx=1)
      (token_type_embeddings): Embedding(1, 1024)
      (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0): RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=1024, out_features=1024, bias=True)
              (key): Linear(in_features=1024, out_features=1024, bias=True)
              (value): Linear(in_features=1024, out_features=1024, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=1024, out_features=1024, bias=True)
         

In [54]:
import nltk
nltk.pos_tag(['their'])

[('their', 'PRP$')]

In [78]:
import torch
import torch.nn as nn
linear = nn.Linear(1024, 3, bias = True)
linear.weight

Parameter containing:
tensor([[ 0.0078,  0.0024,  0.0059,  ..., -0.0015,  0.0047,  0.0023],
        [ 0.0142, -0.0016, -0.0162,  ..., -0.0105, -0.0221, -0.0151],
        [ 0.0159, -0.0172, -0.0093,  ..., -0.0088,  0.0087, -0.0057]],
       requires_grad=True)

In [79]:
linear.bias

Parameter containing:
tensor([ 0.0238, -0.0263, -0.0019], requires_grad=True)

In [80]:
linear.weight = nn.Parameter(linear.weight[0::2,:])

In [82]:
linear.weight

Parameter containing:
tensor([[ 0.0078,  0.0024,  0.0059,  ..., -0.0015,  0.0047,  0.0023],
        [ 0.0159, -0.0172, -0.0093,  ..., -0.0088,  0.0087, -0.0057]],
       requires_grad=True)

In [107]:
from nltk.stem import PorterStemmer

lemm = WordNetLemmatizer()
stemmer = PorterStemmer()
stemmer.stem('Italian')

'italian'

In [1]:
from sklearn.metrics import f1_score

pred = [0,1,2,3,4,5,6]
true = [0,2,2,5,3,5,6]

f1_score(true, pred, average='micro')

0.5714285714285714